tasks:

    - name: install mamba 
      command: |
          wget "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
          bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/mambaforge && rm Mambaforge-$(uname)-$(uname -m).sh
          ../mambaforge/bin/mamba init bash
          source /home/gitpod/.bashrc
          
     - name: install busco 
      command: |
         mamba install -y bioconda::busco
